services:
  web:
    build:
      target: production_build
      args:
        DJANGO_ENV: production
    command: bash ./docker/gunicorn.sh
    environment:
      DOMAIN_NAME: $DOMAIN_NAME
      DJANGO_SECRET_KEY: $DJANGO_SECRET_KEY
      POSTGRES_DB: $POSTGRES_DB
      POSTGRES_USER: $POSTGRES_USER
      POSTGRES_PASSWORD: $POSTGRES_PASSWORD
      DJANGO_DATABASE_HOST: $DJANGO_DATABASE_HOST
      DJANGO_DATABASE_PORT: $DJANGO_DATABASE_PORT
    restart: unless-stopped
    healthcheck:
      test: /bin/sh /code/docker/healthcheck.sh
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s
    ports:
      - "${EXTERNAL_HTTP_PORT:-8000}:8000"
    volumes:
      - ${DJANGO_MEDIA_VOLUME}:/var/www/django/media
      - ${DJANGO_STATIC_VOLUME}:/var/www/django/static
