# Generated by Django 6.0.4 on 2026-05-31 14:49

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('first_name', models.CharField(max_length=64)),
                ('last_name', models.CharField(max_length=64)),
                ('patronymic', models.CharField(blank=True, max_length=64)),
                ('group', models.CharField(blank=True, max_length=32, validators=[django.core.validators.RegexValidator(regex='^((((ИУ|ИБМ|МТ|СМ|БМТ|РЛ|Э|РК|ФН|Л|СГН|РКТ|АК|ПС|РТ|ЛТ|К|ЮР)[1-9]\\d?)|(ЮР(\\.ДК)?))(К)?[ИЦ]?-(((1[0-2])|(\\d))((\\d)|(\\.\\d\\d+))([АМБ]?(В)?)))$')])),
                ('telegram', models.CharField(max_length=32)),
                ('birth_date', models.DateField(blank=True, null=True)),
                ('join_date', models.DateField(auto_now_add=True)),
            ],
            options={
                'constraints': [models.UniqueConstraint(condition=models.Q(('is_deleted', False)), fields=('last_name', 'first_name', 'patronymic'), name='unique_active_fio', nulls_distinct=False), models.UniqueConstraint(condition=models.Q(('is_deleted', False)), fields=('telegram',), name='unique_active_telegram')],
            },
        ),
    ]
