# Generated by Django 6.0.4 on 2026-05-31 15:59

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='telegram',
            field=models.CharField(max_length=32, validators=[django.core.validators.MinLengthValidator(5)]),
        ),
        migrations.CreateModel(
            name='Direction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('name', models.CharField(max_length=128)),
            ],
            options={
                'constraints': [models.UniqueConstraint(condition=models.Q(('is_deleted', False)), fields=('name',), name='unique_active_direction_name')],
            },
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('name', models.CharField(max_length=128)),
                ('direction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='departments', to='members.direction')),
            ],
        ),
        migrations.CreateModel(
            name='Leader',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('position', models.CharField(max_length=128)),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='leaders', to='members.department')),
                ('direction', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='leaders', to='members.direction')),
                ('member', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='leader_role', to='members.member')),
            ],
        ),
        migrations.AddConstraint(
            model_name='department',
            constraint=models.UniqueConstraint(condition=models.Q(('is_deleted', False)), fields=('name', 'direction'), name='unique_active_department_in_direction'),
        ),
        migrations.AddConstraint(
            model_name='leader',
            constraint=models.UniqueConstraint(condition=models.Q(('department__isnull', False), ('is_deleted', False)), fields=('position', 'department'), name='unique_active_position_in_department'),
        ),
        migrations.AddConstraint(
            model_name='leader',
            constraint=models.UniqueConstraint(condition=models.Q(('direction__isnull', False), ('is_deleted', False)), fields=('position', 'direction'), name='unique_active_position_in_direction'),
        ),
        migrations.AddConstraint(
            model_name='leader',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('department_id__isnull', False), ('direction_id__isnull', True)), models.Q(('department_id__isnull', True), ('direction_id__isnull', False)), _connector='OR'), name='check_leader_belongs_to_one_unit'),
        ),
    ]
