# Generated by Django 6.0.4 on 2026-06-01 11:11

from django.contrib.postgres.operations import TrigramExtension
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0002_alter_member_telegram_direction_department_leader_and_more'),
    ]

    operations = [
        TrigramExtension(),
    ]
