# Generated by Django 6.0.4 on 2026-06-01 23:14

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0003_add_pg_trgm'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='departments',
            field=models.ManyToManyField(blank=True, related_name='members', to='members.department'),
        ),
        migrations.AlterField(
            model_name='member',
            name='telegram',
            field=models.CharField(max_length=32, validators=[django.core.validators.RegexValidator(regex='^[a-zA-Z0-9_]{5,32}$')]),
        ),
    ]
