# Generated by Django 6.0.4 on 2026-06-04 08:29

from django.db import migrations


def create_groups_and_permissions(apps, schema_editor):
    """Создает базовые группы и назначает им права (Permissions)."""
    group_model = apps.get_model('auth', 'Group')
    permission_model = apps.get_model('auth', 'Permission')

    members_models = ['direction', 'department', 'member', 'leader']
    auth_models = ['user', 'group']

    roles_matrix = {
        'Viewer': {
            'models': members_models,
            'actions': ['view'],
        },
        'Editor': {
            'models': members_models,
            'actions': [
                'view',
                'add',
                'change',
                'delete',
            ],
        },
        'Admin': {
            'models': members_models + auth_models,
            'actions': [
                'view',
                'add',
                'change',
                'delete',
            ],
        },
    }

    for role_name, config in roles_matrix.items():
        group, _ = group_model.objects.get_or_create(name=role_name)

        codenames = [
            f'{action}_{model}'
            for model in config['models']
            for action in config['actions']
        ]

        permissions = permission_model.objects.filter(codename__in=codenames)
        group.permissions.set(permissions)


def revert_groups_and_permissions(apps, schema_editor):
    """Откат миграции: удаляет созданные группы."""
    group_model = apps.get_model('auth', 'Group')
    group_model.objects.filter(name__in=['Viewer', 'Editor', 'Admin']).delete()


class Migration(migrations.Migration):
    dependencies = [
        ('members', '0004_member_departments_alter_member_telegram'),
    ]

    operations = [
        migrations.RunPython(
            create_groups_and_permissions,
            reverse_code=revert_groups_and_permissions,
        ),
    ]
