# Generated by Django 6.0.4 on 2026-06-04 09:31

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0005_create_default_groups'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='department',
            options={'verbose_name': 'Отдел', 'verbose_name_plural': 'Отделы'},
        ),
        migrations.AlterModelOptions(
            name='direction',
            options={'verbose_name': 'Направление', 'verbose_name_plural': 'Направления'},
        ),
        migrations.AlterModelOptions(
            name='leader',
            options={'verbose_name': 'Руководитель', 'verbose_name_plural': 'Руководители'},
        ),
        migrations.AlterModelOptions(
            name='member',
            options={'verbose_name': 'Активист', 'verbose_name_plural': 'Активисты'},
        ),
        migrations.AlterField(
            model_name='department',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Дата удаления'),
        ),
        migrations.AlterField(
            model_name='department',
            name='direction',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='departments', to='members.direction', verbose_name='Направление'),
        ),
        migrations.AlterField(
            model_name='department',
            name='is_deleted',
            field=models.BooleanField(default=False, verbose_name='Удалено'),
        ),
        migrations.AlterField(
            model_name='department',
            name='name',
            field=models.CharField(max_length=128, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='direction',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Дата удаления'),
        ),
        migrations.AlterField(
            model_name='direction',
            name='is_deleted',
            field=models.BooleanField(default=False, verbose_name='Удалено'),
        ),
        migrations.AlterField(
            model_name='direction',
            name='name',
            field=models.CharField(max_length=128, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='leader',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Дата удаления'),
        ),
        migrations.AlterField(
            model_name='leader',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='leaders', to='members.department', verbose_name='Отдел'),
        ),
        migrations.AlterField(
            model_name='leader',
            name='direction',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='leaders', to='members.direction', verbose_name='Направление'),
        ),
        migrations.AlterField(
            model_name='leader',
            name='is_deleted',
            field=models.BooleanField(default=False, verbose_name='Удалено'),
        ),
        migrations.AlterField(
            model_name='leader',
            name='member',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='leader_role', to='members.member', verbose_name='Активист'),
        ),
        migrations.AlterField(
            model_name='leader',
            name='position',
            field=models.CharField(max_length=128, verbose_name='Должность'),
        ),
        migrations.AlterField(
            model_name='member',
            name='birth_date',
            field=models.DateField(blank=True, null=True, verbose_name='Дата рождения'),
        ),
        migrations.AlterField(
            model_name='member',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Дата удаления'),
        ),
        migrations.AlterField(
            model_name='member',
            name='departments',
            field=models.ManyToManyField(blank=True, related_name='members', to='members.department', verbose_name='Отделы'),
        ),
        migrations.AlterField(
            model_name='member',
            name='first_name',
            field=models.CharField(max_length=64, verbose_name='Имя'),
        ),
        migrations.AlterField(
            model_name='member',
            name='group',
            field=models.CharField(blank=True, max_length=32, validators=[django.core.validators.RegexValidator(regex='^((((ИУ|ИБМ|МТ|СМ|БМТ|РЛ|Э|РК|ФН|Л|СГН|РКТ|АК|ПС|РТ|ЛТ|К|ЮР)[1-9]\\d?)|(ЮР(\\.ДК)?))(К)?[ИЦ]?-(((1[0-2])|(\\d))((\\d)|(\\.\\d\\d+))([АМБ]?(В)?)))$')], verbose_name='Группа'),
        ),
        migrations.AlterField(
            model_name='member',
            name='is_deleted',
            field=models.BooleanField(default=False, verbose_name='Удалено'),
        ),
        migrations.AlterField(
            model_name='member',
            name='join_date',
            field=models.DateField(auto_now_add=True, verbose_name='Дата вступления'),
        ),
        migrations.AlterField(
            model_name='member',
            name='last_name',
            field=models.CharField(max_length=64, verbose_name='Фамилия'),
        ),
        migrations.AlterField(
            model_name='member',
            name='patronymic',
            field=models.CharField(blank=True, max_length=64, verbose_name='Отчество'),
        ),
        migrations.AlterField(
            model_name='member',
            name='telegram',
            field=models.CharField(max_length=32, validators=[django.core.validators.RegexValidator(regex='^[a-zA-Z0-9_]{5,32}$')], verbose_name='Telegram ник'),
        ),
    ]
