# Generated by Django 6.0.4 on 2026-06-04 11:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0006_alter_department_options_alter_direction_options_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='leader',
            name='check_leader_belongs_to_one_unit',
        ),
        migrations.AlterField(
            model_name='leader',
            name='member',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leadership_roles', to='members.member', verbose_name='Активист'),
        ),
    ]
