# Generated by Django 6.0.4 on 2026-06-04 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0007_remove_leader_check_leader_belongs_to_one_unit_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='department',
            name='unique_active_department_in_direction',
        ),
        migrations.RemoveConstraint(
            model_name='direction',
            name='unique_active_direction_name',
        ),
        migrations.RemoveConstraint(
            model_name='leader',
            name='unique_active_position_in_department',
        ),
        migrations.RemoveConstraint(
            model_name='leader',
            name='unique_active_position_in_direction',
        ),
        migrations.RemoveConstraint(
            model_name='member',
            name='unique_active_fio',
        ),
        migrations.RemoveConstraint(
            model_name='member',
            name='unique_active_telegram',
        ),
        migrations.AddConstraint(
            model_name='department',
            constraint=models.UniqueConstraint(condition=models.Q(('deleted_at__isnull', True)), fields=('name', 'direction'), name='unique_active_department_in_direction'),
        ),
        migrations.AddConstraint(
            model_name='direction',
            constraint=models.UniqueConstraint(condition=models.Q(('deleted_at__isnull', True)), fields=('name',), name='unique_active_direction_name'),
        ),
        migrations.AddConstraint(
            model_name='leader',
            constraint=models.UniqueConstraint(condition=models.Q(('deleted_at__isnull', True), ('department__isnull', False)), fields=('position', 'department'), name='unique_active_position_in_department'),
        ),
        migrations.AddConstraint(
            model_name='leader',
            constraint=models.UniqueConstraint(condition=models.Q(('deleted_at__isnull', True), ('direction__isnull', False)), fields=('position', 'direction'), name='unique_active_position_in_direction'),
        ),
        migrations.AddConstraint(
            model_name='member',
            constraint=models.UniqueConstraint(condition=models.Q(('deleted_at__isnull', True)), fields=('last_name', 'first_name', 'patronymic'), name='unique_active_fio', nulls_distinct=False),
        ),
        migrations.AddConstraint(
            model_name='member',
            constraint=models.UniqueConstraint(condition=models.Q(('deleted_at__isnull', True)), fields=('telegram',), name='unique_active_telegram'),
        ),
        migrations.RemoveField(
            model_name='department',
            name='is_deleted',
        ),
        migrations.RemoveField(
            model_name='direction',
            name='is_deleted',
        ),
        migrations.RemoveField(
            model_name='leader',
            name='is_deleted',
        ),
        migrations.RemoveField(
            model_name='member',
            name='is_deleted',
        ),
    ]
