# Generated by Django 6.0.4 on 2026-06-04 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0008_remove_department_unique_active_department_in_direction_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='department',
            name='deleted_at',
            field=models.DateTimeField(blank=True, default=None, null=True, verbose_name='Дата удаления'),
        ),
        migrations.AlterField(
            model_name='direction',
            name='deleted_at',
            field=models.DateTimeField(blank=True, default=None, null=True, verbose_name='Дата удаления'),
        ),
        migrations.AlterField(
            model_name='leader',
            name='deleted_at',
            field=models.DateTimeField(blank=True, default=None, null=True, verbose_name='Дата удаления'),
        ),
        migrations.AlterField(
            model_name='member',
            name='deleted_at',
            field=models.DateTimeField(blank=True, default=None, null=True, verbose_name='Дата удаления'),
        ),
    ]
