# Generated by Django 6.0.4 on 2026-06-04 17:00

from django.db import migrations, models


def truncate_and_deduplicate(apps, schema_editor):
    """Обрезает названия и удаляет дубликаты."""
    Department = apps.get_model('members', 'Department')
    Direction = apps.get_model('members', 'Direction')
    Leader = apps.get_model('members', 'Leader')

    for dept in Department.objects.all():
        truncated = dept.name[:28]
        exists = (
            Department.objects
            .filter(
                direction_id=dept.direction_id,
                name=truncated,
            )
            .exclude(pk=dept.pk)
            .exists()
        )

        if exists:
            dept.name = f'{truncated}_{dept.pk}'
        else:
            dept.name = truncated
        dept.save()

    for dir_obj in Direction.objects.all():
        truncated = dir_obj.name[:32]
        if (
            Direction.objects
            .filter(name=truncated)
            .exclude(pk=dir_obj.pk)
            .exists()
        ):
            dir_obj.name = f'{truncated[:28]}_{dir_obj.pk}'
        else:
            dir_obj.name = truncated
        dir_obj.save()

    for lead in Leader.objects.all():
        lead.position = lead.position[:32]
        lead.save()


class Migration(migrations.Migration):
    dependencies = [
        ('members', '0009_alter_department_deleted_at_and_more'),
    ]

    operations = [
        migrations.RunPython(
            truncate_and_deduplicate,
            reverse_code=migrations.RunPython.noop,
        ),
        migrations.AlterField(
            model_name='department',
            name='name',
            field=models.CharField(max_length=32, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='direction',
            name='name',
            field=models.CharField(max_length=32, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='leader',
            name='position',
            field=models.CharField(max_length=32, verbose_name='Должность'),
        ),
    ]
